[pytest]
markers =
    api: marks tests as API tests
    e2e: marks tests as End-to-End UI tests

[playwright]
# Base URL for the E2E tests. 
# Playwright will automatically prepend this to any relative paths in `page.goto()`.
base_url = "http://127.0.0.1:5500/public"

[api]
# Base URL for the API tests.
base_url = "http://127.0.0.1:8000/api"
